version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - job-tracking-network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   env_file:
  #     - ./frontend/.env
  #   ports:
  #     - '${FRONTEND_PORT}:${FRONTEND_PORT}'
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   networks:
  #     - job-tracking-network

  mongodb:
    image: mongo
    container_name: job-tracking-mongo
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    volumes:
      - mongodb-data:/data/db
    networks:
      - job-tracking-network

volumes:
  mongodb-data:

networks:
  job-tracking-network:
    driver: bridge
